#
###################################
# Site wide configuration
####################################
#
title: Canadian Census Data Discovery Partnership / Partenariat de découverte des données du recensement du Canada
title_en: Canadian Census Data Discovery Partnership
title_fr: Partenariat de découverte des données du recensement du Canada
description: The CDDP-PDDR is a grant-funded project that aims to reduce barriers in the access and use of historical Canadian census data. | Le CDDP-PDDR est un projet financé par des subventions qui vise à réduire les obstacles à l'accès et à l'utilisation des données historiques du recensement canadien.
url: https://cddp-pddr.ca
keywords: ["Canada", "census", "data", "libraries", "recensement"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          #Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->

lang: en
languages: ["en", "fr"]
permalink: pretty

collections:
  posts:
    output: true
    permalink: /:path


#
###################################
# Site Owner configuration
####################################
#
social:
  name_en: Canadian Census Data Discovery Partnership
  name_fr: Partenariat de découverte des données du recensement du Canada
  avatar: #leonids-logo.png
  bio: #"A simple and awesome blog theme powered by jekyll."
  email: census@scholarsportal.info
  twitter: #username
  google:
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: census-recensement
  linkedin: #username
  instagram: #username
  youtube: #username
